pipeline {
    agent any

    environment {
        
        NODE_ENV = 'build'

        hub_org = "muzafferjoya/cert-service"
        registryCredential = 'muzaffar-docker-hub'
        dockerImage = ''
        releaseTag = "release-5.0.0_RC2"
        
        
    }
    
    parameters {
        string(defaultValue: 'release-5.0.0_RC2', description: 'GitHub release tag or branch', name: 'github_release_tag')
    }

    stages {
        
        stage('SCM') {
            steps {
              script {
                  cleanWs()
                  checkout scm: [
                    $class: 'GitSCM',
                    userRemoteConfigs: [[url: 'https://github.com/project-sunbird/cert-service.git']],
                    branches: [[name: "refs/tags/${params.github_release_tag}"]]
                ], poll: false
        }
    }
}
        stage('Initialize') {
            steps {
                script {
                    def mavenHome = tool 'maven'
                    env.PATH = "${mavenHome}/bin:${env.PATH}"
                    env.JAVA_HOME = '/usr/lib/jvm/java-11-openjdk-amd64'

                }
            }
        }
        
        stage('Installing Maven Dep') {
            steps {
                script {
                    
                        sh 'mvn clean install'
                    
                }
            }
        }
        
        stage('Package') {
            steps {
                script {
                    dir('service') {
                        sh 'mvn play2:dist'
                        sh 'cp target/cert-service-1.2.0-dist.zip ../'
                    }
                    sh 'docker build -t ${hub_org}:${releaseTag} .'
                   
                }
            }
        }
        stage('Push Image'){
            steps{
                sh 'docker push ${hub_org}:${releaseTag}'
            }
        }
        
    }
}
