pipeline {
    agent any

    parameters {
        string(name: 'github_release_tag', defaultValue: 'release-4.10.0_RC6', description: 'Specify the GitHub release tag to build from.')
    }
    
    environment {
        hub_org = "muzafferjoya/report-service"
        registryCredential = 'muzaffar-docker-hub'
        dockerImage = ''
        releaseTag = "release-4.10.0_RC6"
    }
    
    stages {        
        stage('Checkout & Build') {
            steps {
                script {
                    cleanWs()
                    checkout scm: [$class: 'GitSCM', userRemoteConfigs: [[url: 'https://github.com/project-sunbird/sunbird-report-service.git']], branches: [[name: 'refs/tags/release-4.10.0_RC6']]], poll: false
                    commit_hash = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
                    build_tag = sh(script: "echo ${params.github_release_tag.split('/')[-1]}_${commit_hash}_${env.BUILD_NUMBER}", returnStdout: true).trim()
                    
                    echo "build_tag: ${build_tag}"
                    
                    env.NODE_ENV = "build"
                    echo "Environment will be : ${env.NODE_ENV}"
                    
                    sh 'git submodule update --init'
                    dockerImage = docker.build("${hub_org}:${releaseTag}")
                }
            }
        }
        stage('Push Image') {
            steps {
                script {
                    docker.withRegistry('', registryCredential) {
                        dockerImage.push("$releaseTag")
                        dockerImage.push('latest')
                    }
                }
            }
        }
    }
}
