pipeline {
    agent any
    
    environment {
        
        hub_org = "muzafferjoya/sunbirdbot"
        registryCredential = 'muzaffar-docker-hub'
        dockerImage = ''
        releaseTag = "release-3.9.0_RC1"
    }
    
    
    stages {
        stage('SCM') {
            steps {
            script {
            checkout scm: [$class: 'GitSCM', userRemoteConfigs: [[url: 'https://github.com/project-sunbird/sunbird-bot.git']], branches: [[name: 'refs/tags/release-3.9.0_RC1']]], poll: false

        }
            }
        }
        stage('Build') {
            environment {
                NODE_ENV = "build"
            }
            steps {
                script {
                    println "Environment will be : ${NODE_ENV}"
                    // build_tag = public_repo_commit_hash + "_" + env.BUILD_NUMBER + "_bot"
                    // if (params.private_bot_repo) {
                    //     sh('cp -r bot_repo/* .')
                    //     build_tag = public_repo_commit_hash + "_" + private_repo_commit_hash + "_" + env.BUILD_NUMBER + "_bot"
                    // }
                    dir('bot') {
                        //sh 'docker build -t ${hub_org}:${BUILD_NUMBER} .'
                        script {
                            //dockerImage = docker.build hub_org
                            dockerImage = docker.build("${hub_org}:${releaseTag}")

                        }
                    }
                }
            }
        }
        stage('Push Image') {
          steps{
            script {
              docker.withRegistry( '', registryCredential ) {
                dockerImage.push("$releaseTag")
                 dockerImage.push('latest')
    
              }
            }
          }
        }
    }
    
}
