pipeline {
    agent any
    
    environment {
        
        hub_org = "muzafferjoya/discussion-middleware"
        registryCredential = 'muzaffar-docker-hub'
        dockerImage = ''
        releaseTag = "release-5.0.0_RC2"
    }
    
    
    stages {
        stage('SCM') {
            steps {
            script {
            checkout scm: [$class: 'GitSCM', userRemoteConfigs: [[url: 'https://github.com/Sunbird-Lern/discussions-middleware.git']], branches: [[name: 'refs/tags/release-5.0.0_RC2']]], poll: false
        }
            }
        }
        stage('Build') {
            environment {
                NODE_ENV = "build"
            }
            steps {
                script {
                    println "Environment will be : ${NODE_ENV}"
                                    }
            }
        }
        stage('Building image') {
          steps{
            script {
              //dockerImage = docker.build hub_org
              dockerImage = docker.build("${hub_org}:${releaseTag}")
            }
          }
        }
        stage('Deploy Image') {
          steps{
            script {
              docker.withRegistry( '', registryCredential ) {
                dockerImage.push("$releaseTag")
                 dockerImage.push('latest')
    
              }
            }
          }
    }
    }
}
