pipeline {
    agent any

    parameters {
        string(name: 'github_release_tag', defaultValue: 'release-4.6.0_RC1', description: 'Specify the GitHub release tag to build from.')
    }

    stages {
        stage('Checkout') {
            steps {
                cleanWs()
                checkout scm: [$class: 'GitSCM', userRemoteConfigs: [[url: 'https://github.com/Sunbird-Knowlg/sunbird-content-player.git']], branches: [[name: 'refs/tags/release-4.6.0_RC1']]], poll: false

                script {
                    commit_hash = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
                    branch_name = sh(script: 'git name-rev --name-only HEAD | rev | cut -d "/" -f1| rev', returnStdout: true).trim()
                    artifact_version = sh(script: "echo " + params.github_release_tag.split('/')[-1] + "_" + commit_hash + "_" + env.BUILD_NUMBER, returnStdout: true).trim()
                    echo "artifact_version: " + artifact_version
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    sh """#!/bin/bash
                    export NVM_DIR="\$HOME/.nvm"
                    [ -s "\$NVM_DIR/nvm.sh" ] && source "\$NVM_DIR/nvm.sh"
                    [ -s "\$NVM_DIR/bash_completion" ] && source "\$NVM_DIR/bash_completion"
                    nvm install 10.16.3
                    cd player
                    npm install
                    npm install grunt
                    npm install grunt-cordovacli grunt-contrib-uglify grunt-contrib-watch grunt-contrib-copy grunt-contrib-compress grunt-aws-s3 grunt-contrib-clean grunt-rename grunt-mkdir grunt-text-replace grunt-karma grunt-jsdoc grunt-contrib-concat grunt-injector --save-dev
                    """
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    sh """#!/bin/bash
                    export NVM_DIR="\$HOME/.nvm"
                    [ -s "\$NVM_DIR/nvm.sh" ] && source "\$NVM_DIR/nvm.sh"
                    [ -s "\$NVM_DIR/bash_completion" ] && source "\$NVM_DIR/bash_completion"
                    nvm use 10.16.3
                    export player_version_number=${branch_name}
                    export build_number=${commit_hash}
                    export filter_plugins=false
                    cd player
                    npm run build-preview ekstep
                    grunt compress:preview
                    grunt generate-libs
                    """
                }
            }
        }
    }
}