pipeline {
    agent any
    
    environment {
        
        hub_org = "muzafferjoya/admin-util"
        registryCredential = 'muzaffar-docker-hub'
        dockerImage = ''
    }
    
    
    stages {
        stage('SCM') {
            steps {
            script {
            checkout scm: [$class: 'GitSCM', userRemoteConfigs: [[url: 'https://github.com/Sunbird-Lern/sunbird-apimanager-util.git']], branches: [[name: 'refs/tags/release-4.5.0_RC3']]], poll: false
            
            def githubReleaseTag = params.github_release_tag ?: 'defaultTag'

            def commit_hash = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
            def build_tag = sh(script: "echo ${githubReleaseTag.split('/')[-1]}_${commit_hash}_${env.BUILD_NUMBER}", returnStdout: true).trim()
            echo "build_tag: ${build_tag}"

            env.NODE_ENV = "build"
            echo "Environment will be: ${env.NODE_ENV}"

        }
            }
        }
        // stage('Build') {
        //     environment {
        //         NODE_ENV = "build"
        //     }
        //     steps {
        //         script {
        //             println "Environment will be : ${NODE_ENV}"
        //         }
        //     }
        // }
        stage('Building image') {
          steps{
            script {
              dockerImage = docker.build hub_org
            }
          }
        }
        stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push("$BUILD_NUMBER")
             dockerImage.push('latest')

          }
        }
      }
    }
        
    }
}
